import {test,expect,vi}from'vitest';
import {loadConfig}from'../src/config.js';import {ShotstackClient}from'../src/api/client.js';import {ALL_TOOLS,validateArguments}from'../src/tools/index.js';import {WriteGuard}from'../src/safety.js';import {mkdir,readFile,stat,writeFile,symlink}from'node:fs/promises';import {mkdtempSync}from'node:fs';import {tmpdir}from'node:os';import {join}from'node:path';
const config=(extra:Record<string,string>={})=>loadConfig({SHOTSTACK_API_KEY:'fixture-key',SHOTSTACK_MIN_REQUEST_INTERVAL_MS:'0',...extra});
const ok=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json'}});
async function call(name:string,args:Record<string,unknown>,client:ShotstackClient){const t=ALL_TOOLS.find(t=>t.name===name)!;validateArguments(t,args);new WriteGuard(client.config).check(t.name,t.risk,args.confirm as boolean,t.title);return t.handler(args,client);}
const edit={timeline:{tracks:[{clips:[{asset:{type:'image',src:'https://example.com/image.png'},start:0,length:1}]}]},output:{format:'mp4',resolution:'sd'}};
test('current catalogue excludes old create origin and unsupported list-assets',()=>{expect(ALL_TOOLS).toHaveLength(23);expect(ALL_TOOLS.filter(t=>t.risk==='read')).toHaveLength(12);expect(ALL_TOOLS.some(t=>t.name==='list_assets')).toBe(false)});
test('read-only direct mutation refused before fetch',async()=>{const f=vi.fn();await expect(call('delete_asset',{id:'fixture',confirm:true},new ShotstackClient(config({SHOTSTACK_READ_ONLY:'1'}),f))).rejects.toThrow('READ_ONLY');expect(f).not.toHaveBeenCalled()});
test('confirmed writes disabled before fetch',async()=>{const f=vi.fn();await expect(call('render',{payload:edit,confirm:true},new ShotstackClient(config({SHOTSTACK_ALLOW_DESTRUCTIVE:'0'}),f))).rejects.toThrow('ALLOW_DESTRUCTIVE');expect(f).not.toHaveBeenCalled()});
test('render approval required before fetch',async()=>{const f=vi.fn();await expect(call('render',{payload:edit},new ShotstackClient(config(),f))).rejects.toThrow('confirm');expect(f).not.toHaveBeenCalled()});
test('valid approved render posts native body to fixed stage environment',async()=>{const f=vi.fn(async()=>ok({response:{id:'render-fixture'}}));await call('render',{payload:edit,confirm:true},new ShotstackClient(config({SHOTSTACK_ENV:'stage'}),f));const [u,i]=f.mock.calls[0] as unknown as [URL,RequestInit];expect(u.href).toBe('https://api.shotstack.io/edit/stage/render');expect(JSON.parse(i.body as string)).toEqual(edit);expect(i.redirect).toBe('error');expect((i.headers as Record<string,string>)['x-api-key']).toBe('fixture-key')});
test('missing timeline/output rejected without network',async()=>{const f=vi.fn();await expect(call('render',{payload:{output:{format:'mp4'}},confirm:true},new ShotstackClient(config(),f))).rejects.toThrow();expect(f).not.toHaveBeenCalled()});
test('nested unknown asset type rejected',async()=>{const f=vi.fn();await expect(call('render',{payload:{...edit,timeline:{tracks:[{clips:[{asset:{type:'invented'},start:0,length:1}]}]}},confirm:true},new ShotstackClient(config(),f))).rejects.toThrow();expect(f).not.toHaveBeenCalled()});
test('serve uses current separate origin with selected account',async()=>{const f=vi.fn(async()=>ok({data:{id:'asset'}}));const c=config({SHOTSTACK_ACCOUNTS:JSON.stringify([{name:'a',api_key:'key-a',env:'stage'},{name:'b',api_key:'key-b',env:'v1'}])});await call('get_asset',{id:'asset-fixture',account:'b'},new ShotstackClient(c,f));const [u,i]=f.mock.calls[0] as unknown as [URL,RequestInit];expect(u.pathname).toBe('/serve/v1/assets/asset-fixture');expect((i.headers as Record<string,string>)['x-api-key']).toBe('key-b')});
test('ingest uses its own base',async()=>{const f=vi.fn(async()=>ok({data:[]}));await call('list_sources',{},new ShotstackClient(config(),f));expect((f.mock.calls[0]as unknown as [URL])[0].pathname).toBe('/ingest/v1/sources')});
test('unknown environment refuses before credentials',()=>{expect(()=>config({SHOTSTACK_ENV:'https://bad.example'})).toThrow('environment');expect(()=>config({SHOTSTACK_ACCOUNTS:'[{"name":"x","env":"dev"}]'})).toThrow('environment')});
test('no reissue of render after uncertain network result',async()=>{const f=vi.fn(async()=>{throw new Error('lost response')});await expect(call('render',{payload:edit,confirm:true},new ShotstackClient(config(),f))).rejects.toThrow();expect(f).toHaveBeenCalledTimes(1)});
test('no retry of mutation on throttling',async()=>{const f=vi.fn(async()=>new Response('{}',{status:429,headers:{'retry-after':'0'}}));await expect(call('delete_template',{id:'fixture',confirm:true},new ShotstackClient(config(),f))).rejects.toThrow();expect(f).toHaveBeenCalledTimes(1)});
test('short read-only 429 can retry with bounded delay',async()=>{let count=0;const sleeps:number[]=[];const f=vi.fn(async()=>++count===1?new Response('{}',{status:429,headers:{'retry-after':'0'}}):ok({models:[]}));await call('list_models',{},new ShotstackClient(config(),f,async(ms)=>{sleeps.push(ms)}));expect(f).toHaveBeenCalledTimes(2);expect(sleeps).toEqual([100])});
test('long retry-after exits without blocking a minute',async()=>{const f=vi.fn(async()=>new Response('{}',{status:429,headers:{'retry-after':'60'}}));await expect(call('list_models',{},new ShotstackClient(config(),f))).rejects.toThrow();expect(f).toHaveBeenCalledTimes(1)});
test('header whitelist refuses credential override',async()=>{const f=vi.fn();await expect(new ShotstackClient(config(),f).request('POST','/generate',[],{},undefined,'edit','application/json',{'x-api-key':'injected'})).rejects.toThrow('header');expect(f).not.toHaveBeenCalled()});
test('generation passes supported idempotency key once',async()=>{const f=vi.fn(async()=>ok({id:'generated'}));await call('generate_asset',{asset:{type:'image',prompt:'fixture',model:'nano-banana-2'},idempotency_key:'test-job-1',confirm:true},new ShotstackClient(config(),f));expect(((f.mock.calls[0]as unknown as [URL,RequestInit])[1].headers as Record<string,string>)['Idempotency-Key']).toBe('test-job-1')});
test('reject path escapes before fetching',async()=>{const f=vi.fn();for(const p of ['//bad.example','/../render','/%2e%2e/render','/%2f%2fbad'])await expect(new ShotstackClient(config(),f).request('GET',p)).rejects.toThrow('path');expect(f).not.toHaveBeenCalled()});
test('probe preserves HTTPS URL as encoded single parameter',async()=>{const f=vi.fn(async()=>ok({metadata:{duration:1}}));await call('probe_media',{url:'https://example.com/clip.mp4'},new ShotstackClient(config(),f));expect((f.mock.calls[0]as unknown as [URL])[0].pathname).toBe('/edit/v1/probe/https%3A%2F%2Fexample.com%2Fclip.mp4')});
test('private regular token file overrides env and gets redacted',async()=>{const dir=mkdtempSync(join(tmpdir(),'shotstack-key-'));const file=join(dir,'key');await writeFile(file,'file-fixture-key',{mode:0o600});const f=vi.fn(async()=>ok({echo:'file-fixture-key',api_key:'file-fixture-key'}));const data=await call('list_models',{},new ShotstackClient(config({SHOTSTACK_TOKEN_FILE:file}),f));expect(JSON.stringify(data)).not.toContain('file-fixture-key');expect(((f.mock.calls[0]as unknown as [URL,RequestInit])[1].headers as Record<string,string>)['x-api-key']).toBe('file-fixture-key')});
test('token symlink refused without network',async()=>{const dir=mkdtempSync(join(tmpdir(),'shotstack-link-'));await writeFile(join(dir,'key'),'fixture',{mode:0o600});await symlink(join(dir,'key'),join(dir,'link'));const f=vi.fn();await expect(call('list_models',{},new ShotstackClient(config({SHOTSTACK_TOKEN_FILE:join(dir,'link')}),f))).rejects.toThrow('private');expect(f).not.toHaveBeenCalled()});
test('upload credential goes to exclusive private JSON file',async()=>{const dir=mkdtempSync(join(tmpdir(),'shotstack-upload-'));const file=join(dir,'upload.json');const f=vi.fn(async()=>ok({url:'https://upload.example/file?X-Amz-Signature=fixture',id:'fixture-source'}));const data=await call('create_upload_url_file',{secret_result_file:file,confirm:true},new ShotstackClient(config(),f));expect(JSON.stringify(data)).not.toContain('X-Amz-Signature');expect(JSON.parse(await readFile(file,'utf8')).url).toContain('X-Amz-Signature');if(process.platform!=='win32')expect((await stat(file)).mode&0o777).toBe(0o600);await expect(call('create_upload_url_file',{secret_result_file:file,confirm:true},new ShotstackClient(config(),f))).rejects.toThrow();expect(f).toHaveBeenCalledTimes(1)});
test('account listing contains environment but no secret/path and has no network',async()=>{const f=vi.fn();const d=await call('list_accounts',{},new ShotstackClient(config(),f));expect(JSON.stringify(d)).toContain('v1');expect(JSON.stringify(d)).not.toContain('fixture-key');expect(f).not.toHaveBeenCalled()});

test('missing Retry-After returns throttle without guessing a minute window',async()=>{const f=vi.fn(async()=>new Response('{}',{status:429}));await expect(call('list_models',{},new ShotstackClient(config(),f))).rejects.toThrow();expect(f).toHaveBeenCalledTimes(1)});

test('malformed account array and non-HTTPS probe refuse locally',async()=>{expect(()=>config({SHOTSTACK_ACCOUNTS:'[null]'})).toThrow('account');const f=vi.fn();await expect(call('probe_media',{url:'http://example.com/a'},new ShotstackClient(config(),f))).rejects.toThrow();expect(f).not.toHaveBeenCalled()});
